version: '3'
services:
  api:
    image: sample-express-app
    build: .
    networks:
      - backend
    ports:
      - "3000:3000"

  web-cli:
    image: sample-express-app
    networks:
      - backend
    command: sh

  mongo:
    container_name: mongodb
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"

networks:
  backend:
    driver: bridge